#!/bin/bash

# =====================================================================
# Ping between two nodes
#
# .. Tip:: Assumes that receiving node has ``bpecho`` running in 
#		   endpoint ipn:x.100 (default)
#
# Parameters
# ----------
# 	$1 = name of sending node (e.g. 1)
#   $2 = name of node being pinged (e.g. 2) 
#
# Usage
# -----
# root@ion_node1: ./bping 1 2
#  	a64 bytes from ipn:1.100  seq=0 time=0.462598 s
#	a64 bytes from ipn:1.100  seq=1 time=0.462485 s
#	a64 bytes from ipn:1.100  seq=2 time=0.465851 s
#	a64 bytes from ipn:1.100  seq=3 time=0.465112 s
#	a64 bytes from ipn:1.100  seq=4 time=0.464634 s
#
# Author:    Marc Sanchez Net
# Date:      01/07/2019
# Copyright: Copyright (c) 2019, Jet Propulsion Laboratory
# =====================================================================

# Make sure ION nodes where node directory is located
export ION_NODE_LIST_DIR="$PWD/nodes"

# Go to this node's directory
cd nodes/$1 2>/dev/null

# If the last operation failed, then the node
# does not exist
if [ $? -eq 1 ]
then
    echo "Node $1 does not exist"
    exit
fi 

# Perform ping. Note that the endpoint ipn:x.100
# contains is bound to bpecho by default
bping ipn:"$1".1 ipn:"$2".100